import 'package:flutter/material.dart';

class AiSummaryDialog extends StatelessWidget {
  final String podcastTitle;
  final String summary;
  final VoidCallback onRegenerateSummary;

  const AiSummaryDialog({
    super.key,
    required this.podcastTitle,
    required this.summary,
    required this.onRegenerateSummary,
  });

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: Text('AI Summary: $podcastTitle'),
      content: Container(
        width: double.maxFinite,
        constraints: BoxConstraints(
          maxHeight:
              MediaQuery.of(context).size.height *
              0.5, // Limit to half the screen height
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Make the summary text scrollable
            Flexible(
              child: SingleChildScrollView(
                child: Text(
                  summary,
                  style: Theme.of(context).textTheme.bodyLarge,
                ),
              ),
            ),
            const SizedBox(height: 16),
            const Text(
              'This summary was generated by Claude AI based on episode descriptions.',
              style: TextStyle(
                fontSize: 12,
                fontStyle: FontStyle.italic,
                color: Colors.grey,
              ),
            ),
          ],
        ),
      ),
      actions: [
        TextButton(
          onPressed: onRegenerateSummary,
          child: const Text('Regenerate'),
        ),
        TextButton(
          onPressed: () {
            Navigator.of(context).pop();
          },
          child: const Text('Close'),
        ),
      ],
    );
  }
}
